namespace TheOtherUs;

public enum CustomRPC : byte
{
    ResetVaribles = 65,
    ForceEnd,
    WorkaroundSetRoles,
    SetRole,
    SetModifier,
    VersionHandshake,
    VersionHandshakeEx,
    UseUncheckedVent,
    UncheckedMurderPlayer,
    UncheckedCmdReportDeadBody,
    UncheckedExilePlayer,
    DynamicMapOption,
    SetGameStarting,
    ShareGamemode,
    StopStart,

    // Role functionality

    EngineerFixLights = 101,
    EngineerFixSubmergedOxygen,
    EngineerUsedRepair,
    CleanBody,
    Mine,
    ShowIndomitableFlash,
    DragBody,
    DropBody,
    MedicSetShielded,
    ShowBodyGuardFlash,
    ShowCultistFlash,
    ShowFollowerFlash,
    ShieldedMurderAttempt,
    TimeMasterShield,
    TimeMasterRewindTime,
    TurnToImpostor,
    BodyGuardGuardPlayer,
    PrivateInvestigatorWatchPlayer,
    PrivateInvestigatorWatchFlash,
    VeterenAlert,
    VeterenKill,
    ShifterShift,
    SwapperSwap,
    MorphlingMorph,
    CamouflagerCamouflage,
    TrackerUsedTracker,
    VampireSetBitten,
    PlaceGarlic,
    GiveBomb,
    DeputyUsedHandcuffs,
    DeputyPromotes,
    JackalCreatesSidekick,
    SidekickPromotes,
    ErasePlayerRoles,
    SetFutureErased,
    SetFutureShifted,
    SetFutureShielded,
    SetFutureSpelled,
    PlaceNinjaTrace,
    PlacePortal,
    AmnisiacTakeRole,
    MimicMimicRole,
    UsePortal,
    CultistCreateImposter,
    TurnToCrewmate,
    PlaceJackInTheBox,
    LightsOut,
    PlaceCamera,
    SealVent,
    ArsonistWin,
    GuesserShoot,
    LawyerSetTarget,
    LawyerPromotesToPursuer,
    BlackmailPlayer,
    UseCameraTime,
    UseVitalsTime,
    UnblackmailPlayer,
    SetBlanked,
    Bloody,
    SetFirstKill,
    SetMeetingChatOverlay,
    SetPosition,
    SetPositionESC,
    SetTiebreak,
    SetInvisibleGen,
    SetSwoop,
    SetInvisible,
    ThiefStealsRole,
    SetTrap,
    TriggerTrap,
    MayorSetVoteTwice,
    PlaceBomb,
    DefuseBomb,

    // Gamemode
    SetGuesserGm,
    HuntedShield,
    HuntedRewindTime,
    SetProp,
    SetRevealed,
    PropHuntStartTimer,
    PropHuntSetInvis,
    PropHuntSetSpeedboost,

    // Other functionality
    ShareTimer,
    ShareGhostInfo,
    
    SendFile,
    RoleRPC,
    Option,
    VoiceChat,
    RPCConnectProject
}